# This is a basic workflow to help you get started with Actions

name: JS Actions

# Controls when the workflow will run
on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
